### ISSUE TITLE
where is the sql file?

### ISSUE THREAD

**Issue by iwebnetid** [yanchummar/FlipTable#1]
there are no database file in this github.where it is?can you provide that ?thank you very much

**Comment by dtg71** [comment]
great work respect! :) yes it would be really great if you could still upload the sql file. thank you from germany!

**Comment by iwebnetid** [comment]
plus.. you server is down too  http://fliptable.co/api/ and http://139.59.19.54/api/restaurants/ too

**Comment by hsnene5** [comment]
@iwebnetid did you solve the problem ?

**Comment by iwebnetid** [comment]
@hsnene5 yes .. you convert all the models into the mysql files based on android and check with the API

**Comment by iwebnetid** [comment]
convert it with gson from google

**Comment by iwebnetid** [comment]
search google how to convert gson into mysql database

**Comment by hsnene5** [comment]
thanks for your help!! Also when I try to run the app It stucks on a page that tells me Ooops. No Internet connection. with try again button. Is it related to database connection ?

**Comment by hsnene5** [comment]
And could you run the whole program ? We need some codes from this project but we couldn't run it.

**Comment by yanchummar** [comment]
Sorry for the delayed response, 
I've added the sql file in the latest commit and yeah the servers are turned off as the project is no longer used in any production environment.

Hope this helps!

**Comment by iwebnetid** [comment]
@yanchummar thank you so much man

**Comment by developer-imran** [comment]
hey buddy! could you tell me how to implement this sql file and api folder?

**Comment by developer-imran** [comment]
![screenshot_2019-01-30-12-25-58-46 1](https://user-images.githubusercontent.com/44571915/51964064-5d8bae00-248b-11e9-846c-e04a10baceb2.png)
I came at this stage and i had added google api and addeda api folder to some web host
