### ISSUE TITLE
Same issue as below?

### ISSUE THREAD

**Issue by developer-imran** [yanchummar/FlipTable#3]
mysql file is required.

**Comment by hsnene5** [comment]
same issue here I don't know how to use the api could you sort it out?

**Comment by yanchummar** [comment]
The SQL file has been added, hope that helps!

**Comment by developer-imran** [comment]
Please we are waiting.

**Comment by yanchummar** [comment]
@imranandroid It has been already added to the repo, please check it out.

**Comment by pouya1380** [comment]
Hi when I import restaurant app Im facing this error reaponse.body().geterror is null plese help me thanks
